# This is a basic workflow to help you get started with Actions

name: CI-Polaris

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, lokesh, macOS]

    env:
      MAC_BRIDGE_URL: "https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/polaris-ci/0.1.81/polaris-ci-0.1.81-macosx.zip"
      LINUX_BRIDGE_URL: "https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-action/0.1.72/ci-package-0.1.72-linux64.zip"
      WINDOWS_BRIDGE_URL: "https://artifactory.internal.synopsys.com/artifactory/clops-local/clops.sig.synopsys.com/polaris-ci/0.1.81/polaris-ci-0.1.81-win64.zip"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use synopsys unified-action
        # Use the action defined in this repository
        uses: ./
        with:
          polaris_serverUrl: "https://cdev.altair.synopsys.com/"
          polaris_accessToken: "3becogven17790dlvqfrv96r9pgrit4r15a4ln4mv8ale2ntp8kh8db79bl2o9fdd2bhgdvpakblu"
          polaris_application_name: "Dev_Application_1"
          polaris_project_name: "Dev_Project_1"
          polaris_assessment_types: '["SAST"]'
          synopsys_bridge_path: "/Users/lokesha/Downloads/ci-package-0.1.67-macosx"