# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, lokesh]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Use synopsys unified-action
        # Use the action defined in this repository
        uses: ./
        with:
          polaris-server-url: ${{ secrets.POLARIS_SEVER_URL }}
          polaris-access-token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris-application-name: "testapp1"
          polaris-project-name: "testproj1"
          polaris-assessment-types: "SAST"

      - name: Use synopsys unified-action - coverity
        # Use the action defined in this repository
        uses: ./
        with:
          coverity-url: ${{ secrets.COVERITY_URL }}
          coverity-user: ${{ secrets.COVERITY_USER }}
          coverity-pasphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          coverity-project-name: ${{ secrets.COVERITY_PASSPHRASE }}
